apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qwik
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-qwik@sha256:a9007b67f178d3c81a0b2002a7575ba48c4518adb694e5768cecc2e331074da6
        name: my-nodejs
        resources: {}
status: {}
